### ISSUE TITLE
Investigate Appveyor (Windows-only?) error

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#774]
A non-fatal error is occurring in Appveyor:

https://ci.appveyor.com/project/MaidSafe-QA/safe-client-libs/builds/20116224#L1584

Try reproducing this locally on a Windows machine, determine if the error is a sign of an underlying problem, and implement a fix.

```
cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_authenticator/Cargo.toml

...
thread '<unnamed>' panicked at '
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   unwrap! called on Result::Err                                              !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
safe_core\src\client\mock\routing.rs:1130,44 in safe_core::client::mock::routing
Err("SendError(..)")
', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\unwrap-1.2.1\src\lib.rs:67:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at libstd\sys\windows\backtrace/mod.rs:104
             at libstd\sys\windows\backtrace/mod.rs:91
   1: std::sys_common::backtrace::print
             at libstd\sys_common/backtrace.rs:71
             at libstd\sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: <core::result::Result<T, E> as unwrap::VerboseUnwrap>::verbose_unwrap
test client::tests::restart_routing ... ok
test client::tests::seeded_login ... ok
```

**Comment by S-Coyle** [comment]
Closing - Appveyor no longer in use
